dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decideheroku-travis
  strategy: git
  api_key:
    secure: YaymTo1p31Gh3VaSRYTAEBBdO7N9RlRY/25p1R999zF4K1fU9fo9t0MxF/7ceblbxZLW4UAMfp05kkCpsf+FL58U+9UTt0m/VPptcjW+7s10y+mR31a+OlL3Wx4lWo+E/kcKHhqCG/8OvJt1Z7J64yJtpSa33P5HrA/xxzyX28FhqZGpl8Cq7bw3tp/fi4NsLDvzd2OnrcFQ7bYLU6Qkm9L1nxHVGLSsnFgRpa/b25IdRxcPJm4Dn1ZnqP9jVtHwaGZqcazvuhHAzEbiYaXA2Krjzgo9wm9Iz/Tbei6ICXQUWE/DSliLCd+IcqpEKDx7Wf9xGs/fAFcPn+JG34j8ETJXQZkEC+lTI14jixAtE7pTtWLfZarrtsBUBQvwIlfAfO3O0A9qzPrm1fzQKFUX2TkNCeZSCCY3EDowVQdbT39BV0Mm1WvcuAEwOy/zo91Xl7Oll/iZv4KvgjfIsJk0luCyqHMa3IEPMUXRbIpJMZUYKPbH69M4QL9xFlQFn7pynqEL1K8VDEJsXdLrQlhCird4AKKyPlTHF57O0MllkBkub/sGAtCq38Vm1aMC4y0sklyPO1ZAqk0ARUNy8ZAMzB42+bXGrAfyMR+73NJMKtoSaaE1DRiVQEpiZ1D+f2ulU3dzKkE9M0ksxqd7Wp4g7HF9Z+yXe0LbLLaWEEd6PRU=
